Ticks_After_Bitten: 5
Ticks_After_Caught: 20
Ticks_Before_Timeout: 1200
Only_Specific_Rod:
  Enable: false
  Rod_Name: "&6Auto Fishing Rod"
  Rod_Lore:
    - "&fUse this to Auto-Fishing."
  Rod_Model_Data: 0

# Enchantment that prevents automatic fishing rods from being applied at an anvil
# Remove the "#" at the beginning of the line for the enchantment you want to block.
Blocked_Enchantments:
#  - "MENDING"
#  - "UNBREAKING"
#  - "LURE"
#  - "LUCK_OF_THE_SEA"
#  - "VANISHING_CURSE"
